# ------------------------------
# .github/workflows/deploy.yml
# ------------------------------
name: Build and Deploy ShadowDex Escrow
on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/shadowdex-escrow:latest
          cache-from: type=registry,ref=${{ secrets.REGISTRY_URL }}/shadowdex-escrow:buildcache
          cache-to: type=registry,mode=max,ref=${{ secrets.REGISTRY_URL }}/shadowdex-escrow:buildcache

      - name: Trigger Deploy
        run: curl -fsSL -X POST ${{ secrets.DEPLOY_HOOK }}
